### ISSUE TITLE
Does this truely require php7?

### ISSUE THREAD

**Issue by Leapfrognz** [jsmitty12/phpWhois#18]
Recently you have added the php>7 requirement to composer. Is that really true? I had this working pretty well in 5.6 before the php dependency was added to composer.

**Comment by jsmitty12** [comment]
Hello. Sorry for not getting back to you sooner. I decided to require php > 7 primarily because php 5.6 (and php 7.0 as well) is only receiving security updates through the end of this year. I also wanted to be able to use some php 7+ features (which I don't think I've added outside the `testsuite.php` file yet).

I would be willing to accept a PR to add php 5.6 support again assuming the TravisCI build passes.
